<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJNBF12\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJNBF12/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJNBF12.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJNBF12\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRJNBF12\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RJNBF12',
    'container.build_id' => '277660ba',
    'container.build_time' => 1576505523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJNBF12');
