<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP8j1MNt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP8j1MNt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP8j1MNt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP8j1MNt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP8j1MNt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P8j1MNt',
    'container.build_id' => '46445119',
    'container.build_time' => 1574843521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP8j1MNt');
